# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=6)),
                ('installdate', models.DateTimeField(verbose_name='date published')),
                ('boot_mode', models.CharField(choices=[('BIOS', 'BIOS'), ('UEFI', 'UEFI')], default='BIOS', max_length=4)),
            ],
        ),
    ]
