# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='hostname',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
