# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_auto_20161112_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='System Manufacturer'),
        ),
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.CharField(default='None', max_length=100, verbose_name='Assigned User'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='boot_mode',
            field=models.CharField(choices=[('BIOS', 'BIOS'), ('UEFI', 'UEFI')], default='BIOS', max_length=4, verbose_name='Boot Mode'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='installdate',
            field=models.DateField(verbose_name='Install Date'),
        ),
    ]
