# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0005_auto_20161112_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='service_tag',
            field=models.CharField(default='Unknown', max_length=6, verbose_name='Service Tag'),
        ),
    ]
