# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0006_machine_service_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='architecture',
            field=models.CharField(default='x64', max_length=6, verbose_name='Architecture'),
        ),
    ]
