# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0007_machine_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='RAM',
            field=models.CharField(default='Unknown', max_length=10, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='machine',
            name='cpu',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='architecture',
            field=models.CharField(choices=[('x86', 'x86'), ('x64', 'x64')], default='x64', max_length=3, verbose_name='Architecture'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True, verbose_name='MAC Address'),
        ),
    ]
